- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  with_items:
    - ca-certificates
    - openssl
    - php-mbstring
    - php-sqlite3
    - php-xml
    - php7.0-gd
    - rsync
    - tar
    - unzip
    - zip
